### ISSUE TITLE
[SAM] Improve beanstalk security: introduce new vpc and subnet.

### ISSUE THREAD

**Issue by binchoo** [binchoo/PaimonGanyu#16]
**As-is:**
I have my beanstalk application inside the "default VPC & subnet".
- If the ALB endpoint is exposed accidentally, this becomes a critical security problem. Because a malicious user can request any delete operation for resources of others via the exposed URL.

~~**To-be:**~~
- [ ] ~~Make a private subnet and deploy the beanstalk app there.~~
- [ ] ~~Configure a VPC Endpoint for DynamoDB.~~

**Comment by binchoo** [comment]
You may just configure the Spring Security.

**Comment by binchoo** [comment]
## Creating a new SG for ikakao proxies
```yaml
  SGIkakaoBotProxy:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security Group allowing inbound traffic from ikakao bot proxies"
      GroupName: SGIkakaoBotProxy
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 219.249.231.40/30

  PaimonGanyuSkillConfigurationTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      Description: Configuration for PaimonGanyu KAKAOTALK Skill Server
      ApplicationName: !Ref PaimonGanyuSkillApplication
      SolutionStackName: 64bit Amazon Linux 2 v3.2.16 running Corretto 11
      OptionSettings:
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: IamInstanceProfile
          Value: !Ref PaimonGanyuSkillInstanceProfile
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: SecurityGroups
          Value: !Ref SGIkakaoBotProxy
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: EnvironmentType
          Value: SingleInstance
```
