### ISSUE TITLE
[SAM] Review templates and find points to replace with Mappings data

### ISSUE THREAD

**Issue by binchoo** [binchoo/PaimonGanyu#23]
**To-be:**
The overall goal is to find an elegant way to provide test/prod environments to the PaimonGanyu's architecture.
- Have two different AWS accounts per test/prod environment.
- The [Mappings](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/mappings-section-structure.html) area isn't currently in use. Review and find some points that mapping data can replace.
- ~~Consider using [Lambda alias](https://docs.aws.amazon.com/lambda/latest/dg/configuration-aliases.html) to provide test/prod environments for the workflows in the `paimonganyu` stack.~~ Two siloed accounts will separate the environments.

**Comment by binchoo** [comment]
## Change of Impact

### New DNS Hosted Zones
- I acquired a new domain name for PaimonGanyu: `paimon.studio`. The name of it was considered for future business.

### New AWS Account for Test Environment
- PaimonGanyu is manged by two AWS accounts per environment(test/prod).
  - Test environment manger - `paimonganyu-test:pgtest`
  - Production environment manager - `jbinchoo-aws:pgprod`

### Third-Level Domain for Test Environment in the New Account
- The new account `paimonganyu-test` created a Route 53 Hosted Zone - `test.paimon.studio`. It manages DNS records for instances in the test environment.
- To resolve `(*.)test.paimong.studio` domain names, `jbinchoo-aws` created an `NS` record within its `paimon.studio` hosted zone, which will propagate DNS requests to the name servers that `test.paimon.studio` hosted zone of  `paimonganyu-test` account has.

### Mappings and Conditions with CFN templates
```
Parameters:
  Env:
    Type: String
    Default: test
    AllowedValues:
      - test
      - prod
    Description: The enviroment type of this deployment.

  UseALB:
    Type: String
    Default: 'False'
    AllowedValues:
      - 'True'
      - 'False'
    Description: Whether to create an ALB. If Env=prod, an ALB is always created.

Conditions:
  CreateProd: !Equals [!Ref Env, prod]
  CreateALB: !Or [Condition: CreateProd, !Equals [!Ref UseALB, 'True']]

Mappings:
  EnvMap:
    HostedZone:
      prod: paimon.studio.
      test: test.paimon.studio.
    ApiDomain:
      prod: skill.paimon.studio
      test: skill.test.paimon.studio

  RegionEnvMap:
    ap-northeast-2:
      prod: SeoulProd
      test: SeoulTest
    ap-northeast-1:
      prod: TokyoProd
      test: TokyoTest
    CACert:
      SeoulProd: arn:aws:acm:ap-northeast-2:305992497901:certificate/9023abac-1279-4647-8056-ec5be058af4c
      SeoulTest: arn:aws:acm:ap-northeast-2:254804608366:certificate/3ee23337-94cb-47ba-9ce4-b91c0b71ac1b
      TokyoProd: arn:aws:acm:ap-northeast-1:305992497901:certificate/eb2ba354-e8c3-49ec-836d-5003be9c0da7
```

### CFN Templates' Locations
CFN templates for `paimonganyu` and `paimonganyu-skill` stacks exist inside their own gradle project's root directory.

### Gradle Tasks Cares SAM Build & Deploy
Instead of a Makefile, Gradle tasks take responsibility to exec sam build & deploy cli commands.
