### ISSUE TITLE
(awsutils) Define a DSL for event wrapper mappings.

### ISSUE THREAD

**Issue by binchoo** [binchoo/paimonganyu#3]
# Customizing Event Wrapper Mappings

## DSL definitions

Here defines the basic stucture of DSL that configures event wrapper mappings in YAML format. **However, this is only to draw the conceptual structure** in human-readable manner. The actual DSL is implemented by java objects.

### DSL

```yaml
WrappingManual:
  wrappingManual (required)
```

### WrappingManual

```yaml
mappingEntries
```

### MappingEntries

```yaml
- mappingEntry (required)
- mappingEntry (optional)
- ...
```

### MappingEntry

```yaml
Event: S3Event|SQSEvent|SNSEvent|DynamodbEvent| ... (required)
Condition: !Predicate (event)-> ... (optional)
WrapperSpec:
  wrapperSpec (required)
```

### WrapperSpec

```yaml
Wrapper: AwsEventWrapper<S3Event>| AwsEventWrapper<SQSEvent>| ... (required)
ConstructorArgs: (optional)
  - argType
  - argType
  - ...
```

### An example

```yaml
WrappingManual:
  - Event: SQSEvent
    WrapperSpec:
      Wrapper: SQSEventWrapper
  - Event: S3Event
    Condition: !Predicate (event)-> event.records.anyMatch(r-> r.s3.object.key.contains(".json"))
    WrapperSpec:
      Wrapper: S3EventObjectReader
      ConstructorArgs:
        - AmazonS3
```

**Comment by binchoo** [comment]
# Customizing Event Wrapper Mappings

## DSL definitions

Here defines the basic stucture of DSL that configures event wrapper mappings in YAML format. **However, this is only to draw the conceptual structure** in human-readable manner. The actual DSL is implemented by java objects.

### Top-level view

```yaml
WrappingManual:
  wrappingManual (required)
```

### WrappingManual

```yaml
mappingEntries
```

### MappingEntries

```yaml
- mappingEntry (required)
- mappingEntry (optional)
- ...
```

### MappingEntry

```yaml
Event: S3Event|SQSEvent|SNSEvent|DynamodbEvent| ... (required)
Condition: !Predicate (event)-> ... (optional)
WrapperSpec:
  wrapperSpec (required)
```

### WrapperSpec

```yaml
Wrapper: AwsEventWrapper<S3Event>| AwsEventWrapper<SQSEvent>| ... (required)
ConstructorArgs: (optional)
  - argType
  - argType
  - ...
```

### An example

```yaml
WrappingManual:
  - Event: SQSEvent
    WrapperSpec:
      Wrapper: SQSEventWrapper
  - Event: S3Event
    Condition: !Predicate (event)-> event.records.anyMatch(r-> r.s3.object.key.contains(".json"))
    WrapperSpec:
      Wrapper: S3EventObjectReader
      ConstructorArgs:
        - AmazonS3
```

## Java implementation

```java
manual // AwsEventWrapperManual
    .whenEvent(SQSEvent.class) // MappingEntry<SQSEvent>
    	.wrapBy(SQSEventWrapper.class) // WrapperSpec<SQSEventWrapper>
    .and() // AwsEventWrapperManual
    .whenEvent(S3Event.class).satisfies(new IsJsonObject()) // MappingEntry<S3Event>
    	.wrapBy(S3EventObjectReader.class).argTypes(AmazonS3.class) // WrapperSpec<SQSEventWrapper>
    ;
```
