### ISSUE TITLE
[SAM] Parameterize template.yaml to split prod/stage environments.

### ISSUE THREAD

**Issue by binchoo** [binchoo/PaimonGanyu#8]

**Comment by binchoo** [comment]
## Create a `Env` parameter

```yaml
Parameters:
  Env:
    Type: String
    AllowedValues: 
       - prod
       - test
```

## Create a `IsProd` condition
```yaml
Conditions:
  IsProd: !Equals
    - !Ref Env
    - prod
```

## Use the `!If` intrinsic function to configure differently per environment
```yaml
Resources:
  PaimonGanyuSpringBootApp:
    Type: AWS::Serverless::Function
    Properties:
      …
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: !If [IsProd, 3, 1]
      DeploymentPreference:
        Type: AllAtOnce
```
